# Site settings
title: Saylor Academy - GitHub Courses
email: contact@saylor.org
description: > # this means to ignore newlines until "baseurl:"
  Saylor Academy's Legacy Courseware
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: saylordotorg
github_username:  saylordotorg
facebook_username: SaylorFoundation
googleplus_username: 105426497265909285606

# Build settings
markdown: kramdown
#permalink: /:title/

collections:
  course_arth101:
    output: true
    permalink: /arth101/:path/
    label: ARTH101
  course_arth110:
    output: true
    permalink: /arth110/:path/
    label: ARTH110
  course_arth111:
    output: true
    permalink: /arth111/:path/
    label: ARTH111
  course_arth201:
    output: true
    permalink: /arth201/:path/
    label: ARTH201
  course_arth202:
    output: true
    permalink: /arth202/:path/
    label: ARTH202
  course_arth206:
    output: true
    permalink: /arth206/:path/
    label: ARTH206
  course_arth207:
    output: true
    permalink: /arth207/:path/
    label: ARTH207
  course_arth208:
    output: true
    permalink: /arth208/:path/
    label: ARTH208
  course_arth209:
    output: true
    permalink: /arth209/:path/
    label: ARTH209
  course_arth210:
    output: true
    permalink: /arth210/:path/
    label: ARTH210
  course_arth301:
    output: true
    permalink: /arth301/:path/
    label: ARTH301
  course_arth303:
    output: true
    permalink: /arth303/:path/
    label: ARTH303
  course_arth304:
    output: true
    permalink: /arth304/:path/
    label: ARTH304
  course_arth305:
    output: true
    permalink: /arth305/:path/
    label: ARTH305
  course_arth307:
    output: true
    permalink: /arth307/:path/
    label: ARTH307
  course_arth401:
    output: true
    permalink: /arth401/:path/
    label: ARTH401
  course_arth406:
    output: true
    permalink: /arth406/:path/
    label: ARTH406
  course_arth408:
    output: true
    permalink: /arth408/:path/
    label: ARTH408
  course_arth409:
    output: true
    permalink: /arth409/:path/
    label: ARTH409
  course_astr101:
    output: true
    permalink: /astr101/:path/
    label: ASTR101
  course_bio101a:
    output: true
    permalink: /bio101a/:path/
    label: BIO101A
  course_bio101b:
    output: true
    permalink: /bio101b/:path/
    label: BIO101B
  course_bio101l:
    output: true
    permalink: /bio101l/:path/
    label: BIO101L
  course_bio102:
    output: true
    permalink: /bio102/:path/
    label: BIO102
  course_bio102l:
    output: true
    permalink: /bio102l/:path/
    label: BIO102
  course_bio301:
    output: true
    permalink: /bio301/:path/
    label: BIO301
  course_bio302:
    output: true
    permalink: /bio302/:path/
    label: BIO302
  course_bio302l:
    output: true
    permalink: /bio302l/:path/
    label: BIO302L
  course_bio303:
    output: true
    permalink: /bio303/:path/
    label: BIO303
  course_bio304:
    output: true
    permalink: /bio304/:path/
    label: BIO304
  course_bio304l:
    output: true
    permalink: /bio304l/:path/
    label: BIO304L
  course_cs407:
    output: true
    permalink: /cs407/:path/
    label: CS407