# Site settings
title: Saylor Academy - GitHub Courses
email: contact@saylor.org
description: > # this means to ignore newlines until "baseurl:"
  Saylor Academy's Legacy Courseware
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: saylordotorg
github_username:  saylordotorg
facebook_username: SaylorFoundation
googleplus_username: 105426497265909285606

# Build settings
markdown: kramdown
#permalink: /:title/

collections:
  course_arth101:
    output: true
    permalink: /arth101/:path/
    label: ARTH101
  course_arth110:
    output: true
    permalink: /arth110/:path/
    label: ARTH110
  course_arth111:
    output: true
    permalink: /arth111/:path/
    label: ARTH111
  course_arth201:
    output: true
    permalink: /arth201/:path/
    label: ARTH201
  course_arth202:
    output: true
    permalink: /arth202/:path/
    label: ARTH202
  course_arth206:
    output: true
    permalink: /arth206/:path/
    label: ARTH206
  course_arth207:
    output: true
    permalink: /arth207/:path/
    label: ARTH207
  course_arth208:
    output: true
    permalink: /arth208/:path/
    label: ARTH208
  course_arth209:
    output: true
    permalink: /arth209/:path/
    label: ARTH209
  course_arth210:
    output: true
    permalink: /arth210/:path/
    label: ARTH210
  course_arth301:
    output: true
    permalink: /arth301/:path/
    label: ARTH301
  course_arth303:
    output: true
    permalink: /arth303/:path/
    label: ARTH303
  course_arth304:
    output: true
    permalink: /arth304/:path/
    label: ARTH304
  course_arth305:
    output: true
    permalink: /arth305/:path/
    label: ARTH305
  course_arth307:
    output: true
    permalink: /arth307/:path/
    label: ARTH307
  course_arth401:
    output: true
    permalink: /arth401/:path/
    label: ARTH401
  course_arth406:
    output: true
    permalink: /arth406/:path/
    label: ARTH406
  course_arth408:
    output: true
    permalink: /arth408/:path/
    label: ARTH408
  course_arth409:
    output: true
    permalink: /arth409/:path/
    label: ARTH409
  course_astr101:
    output: true
    permalink: /astr101/:path/
    label: ASTR101
  course_bio101a:
    output: true
    permalink: /bio101a/:path/
    label: BIO101A
  course_bio101b:
    output: true
    permalink: /bio101b/:path/
    label: BIO101B
  course_bio101l:
    output: true
    permalink: /bio101l/:path/
    label: BIO101L
  course_bio102:
    output: true
    permalink: /bio102/:path/
    label: BIO102
  course_bio102l:
    output: true
    permalink: /bio102l/:path/
    label: BIO102
  course_bio301:
    output: true
    permalink: /bio301/:path/
    label: BIO301
  course_bio302:
    output: true
    permalink: /bio302/:path/
    label: BIO302
  course_bio302l:
    output: true
    permalink: /bio302l/:path/
    label: BIO302L
  course_bio303:
    output: true
    permalink: /bio303/:path/
    label: BIO303
  course_bio304:
    output: true
    permalink: /bio304/:path/
    label: BIO304
  course_bio304l:
    output: true
    permalink: /bio304l/:path/
    label: BIO304L
  course_bio305:
    output: true
    permalink: /bio305/:path/
    label: BIO305
  course_bio306:
    output: true
    permalink: /bio306/:path/
    label: BIO306
  course_bio307:
    output: true
    permalink: /bio307/:path/
    label: BIO307
  course_bio308:
    output: true
    permalink: /bio308/:path/
    label: BIO308
  course_bio309:
    output: true
    permalink: /bio309/:path/
    label: BIO309
  course_bio310:
    output: true
    permalink: /bio310/:path/
    label: BIO310
  course_bio311:
    output: true
    permalink: /bio311/:path/
    label: BIO311
  course_bio312:
    output: true
    permalink: /bio312/:path/
    label: BIO312
  course_bio313:
    output: true
    permalink: /bio313/:path/
    label: BIO313
  course_bio401:
    output: true
    permalink: /bio401/:path/
    label: BIO401
  course_bio402:
    output: true
    permalink: /bio402/:path/
    label: BIO402
  course_bio403:
    output: true
    permalink: /bio403/:path/
    label: BIO403
  course_bio404:
    output: true
    permalink: /bio404/:path/
    label: BIO404
  course_bio405:
    output: true
    permalink: /bio405/:path/
    label: BIO405
  course_bio406:
    output: true
    permalink: /bio406/:path/
    label: BIO406
  course_bio407:
    output: true
    permalink: /bio407/:path/
    label: BIO407
  course_bus101:
    output: true
    permalink: /bus101/:path/
    label: BUS101
  course_bus103:
    output: true
    permalink: /bus103/:path/
    label: BUS103
  course_bus105:
    output: true
    permalink: /bus105/:path/
    label: BUS105
  course_bus202:
    output: true
    permalink: /bus202/:path/
    label: BUS202
  course_bus203:
    output: true
    permalink: /bus203/:path/
    label: BUS203
  course_bus204:
    output: true
    permalink: /bus204/:path/
    label: BUS204
  course_bus205:
    output: true
    permalink: /bus205/:path/
    label: BUS205
  course_bus206:
    output: true
    permalink: /bus206/:path/
    label: BUS206
  course_bus208:
    output: true
    permalink: /bus208/:path/
    label: BUS208
  course_bus209: 
    output: true
    permalink: /bus209/:path/
    label: BUS209
  course_bus210:
    output: true
    permalink: /bus210/:path/
    label: BUS210
  course_bus300:
    output: true
    permalink: /bus300/:path/
    label: BUS300
  course_bus301:
    output: true
    permalink: /bus301/:path/
    label: BUS301
  course_bus303:
    output: true
    permalink: /bus303/:path/
    label: BUS303
  course_bus305:
    output: true
    permalink: /bus305/:path/
    label: BUS305
  course_bus306:
    output: true
    permalink: /bus306/:path/
    label: BUS306
  course_bus401:
    output: true
    permalink: /bus401/:path/
    label: BUS401
  course_bus402:
    output: true
    permalink: /bus402/:path/
    label: BUS402
  course_bus403:
    output: true
    permalink: /bus403/:path/
    label: BUS403
  course_bus404:
    output: true
    permalink: /bus404/:path/
    label: BUS404
  course_bus501:
    output: true
    permalink: /bus501/:path/
    label: BUS501
  course_chem101:
    output: true
    permalink: /chem101/:path/
    label: CHEM101
  course_chem102:
    output: true
    permalink: /chem102/:path/
    label: CHEM102
  course_chem103:
    output: true
    permalink: /chem103/:path/
    label: CHEM103
  course_chem104:
    output: true
    permalink: /chem104/:path/
    label: CHEM104
  course_chem105:
    output: true
    permalink: /chem105/:path/
    label: CHEM105
  course_chem106:
    output: true
    permalink: /chem106/:path/
    label: CHEM106
  course_chem107:
    output: true
    permalink: /chem107/:path/
    label: CHEM107
  course_chem108:
    output: true
    permalink: /chem108/:path/
    label: CHEM108
  course_chem201:
    output: true
    permalink: /chem201/:path/
    label: CHEM201
  course_chem202:
    output: true
    permalink: /chem202/:path/
    label: CHEM202
  course_chem203:
    output: true
    permalink: /chem203/:path/
    label: CHEM203
  course_chem204:
    output: true
    permalink: /chem204/:path/
    label: CHEM204
  course_chem205:
    output: true
    permalink: /chem205/:path/
    label: CHEM205
  course_comm001:
    output: true
    permalink: /comm001/:path/
    label: COMM001
  course_comm002:
    output: true
    permalink: /comm002/:path/
    label: COMM002
  course_comm101:
    output: true
    permalink: /comm101/:path/
    label: COMM101
  course_comm103:
    output: true
    permalink: /comm103/:path/
    label: COMM103
  course_comm311:
    output: true
    permalink: /comm311/:path/
    label: COMM311
  course_comm323:
    output: true
    permalink: /comm323/:path/
    label: COMM323
  course_comm411:
    output: true
    permalink: /comm411/:path/
    label: COMM411
  course_commoncore101:
    output: true
    permalink: /commoncore101/:path/
    label: COMMONCORE101
  course_cs101:
    output: true
    permalink: /cs101/:path/
    label: CS101
  course_cs102:
    output: true
    permalink: /cs102/:path/
    label: CS102
  course_cs107:
    output: true
    permalink: /cs107/:path/
    label: CS107
  course_cs201:
    output: true
    permalink: /cs201/:path/
    label: CS201
  course_cs202:
    output: true
    permalink: /cs202/:path/
    label: CS202
  course_cs301:
    output: true
    permalink: /cs301/:path/
    label: CS301
  course_cs302:
    output: true
    permalink: /cs302/:path/
    label: CS302
  course_cs303:
    output: true
    permalink: /cs303/:path/
    label: CS303
  course_cs304:
    output: true
    permalink: /cs304/:path/
    label: CS304
  course_cs305:
    output: true
    permalink: /cs305/:path/
    label: CS305
  course_cs401:
    output: true
    permalink: /cs401/:path/
    label: CS401
  course_cs402:
    output: true
    permalink: /cs402/:path/
    label: CS402
  course_cs403:
    output: true
    permalink: /cs403/:path/
    label: CS403
  course_cs404:
    output: true
    permalink: /cs404/:path/
    label: CS404
  course_cs405:
    output: true
    permalink: /cs405/:path/
    label: CS405
  course_cs406:
    output: true
    permalink: /cs406/:path/
    label: CS406
  course_cs407:
    output: true
    permalink: /cs407/:path/
    label: CS407
  course_cs408:
    output: true
    permalink: /cs408/:path/
    label: CS408
  course_cs409:
    output: true
    permalink: /cs409/:path/
    label: CS409
  course_cs410:
    output: true
    permalink: /cs410/:path/
    label: CS410
  course_cs411:
    output: true
    permalink: /cs411/:path/
    label: CS411
  course_cs412:
    output: true
    permalink: /cs412/:path/
    label: CS412
  course_cust104:
    output: true
    permalink: /cust104/:path/
    label: CUST104
  course_cust105:
    output: true
    permalink: /cust105/:path/
    label: CUST105
  course_econ101:
    output: true
    permalink: /econ101/:path/
    label: ECON101
  course_econ101_clep:
    output: true
    permalink: /econ101-clep/:path/
    label: ECON101-CLEP
  course_econ102:
    output: true
    permalink: /econ102/:path/
    label: ECON102
  course_econ102_exc:
    output: true
    permalink: /econ102-exc/:path/
    label: ECON102-EXC
  course_econ200:
    output: true
    permalink: /econ200/:path/
    label: ECON200
  course_econ201:
    output: true
    permalink: /econ201/:path/
    label: ECON201
  course_econ202:
    output: true
    permalink: /econ202/:path/
    label: ECON202
  course_econ301:
    output: true
    permalink: /econ301/:path/
    label: ECON301
  course_econ302:
    output: true
    permalink: /econ302/:path/
    label: ECON302
  course_econ303:
    output: true
    permalink: /econ303/:path/
    label: ECON303
  course_econ304:
    output: true
    permalink: /econ304/:path/
    label: ECON304
  course_econ305:
    output: true
    permalink: /econ305/:path/
    label: ECON305
  course_econ306:
    output: true
    permalink: /econ306/:path/
    label: ECON306
  course_econ307:
    output: true
    permalink: /econ307/:path/
    label: ECON307
  course_engl000:
    output: true
    permalink: /engl000/:path/
    label: ENGL000
  course_engl001:
    output: true
    permalink: /engl001/:path/
    label: ENGL001
  course_engl002:
    output: true
    permalink: /engl002/:path/
    label: ENGL002
  course_engl101:
    output: true
    permalink: /engl101/:path/
    label: ENGL101
  course_engl201:
    output: true
    permalink: /engl201/:path/
    label: ENGL201
  course_engl202:
    output: true
    permalink: /engl202/:path/
    label: ENGL202
  course_engl203:
    output: true
    permalink: /engl203/:path/
    label: ENGL203
  course_engl204:
    output: true
    permalink: /engl204/:path/
    label: ENGL204
  course_engl301:
    output: true
    permalink: /engl301/:path/
    label: ENGL301
  course_engl401:
    output: true
    permalink: /engl401/:path/
    label: ENGL401
  course_engl402:
    output: true
    permalink: /engl402/:path/
    label: ENGL402
  course_engl403:
    output: true
    permalink: /engl403/:path/
    label: ENGL403
  course_engl404:
    output: true
    permalink: /engl404/:path/
    label: ENGL404
  course_engl405:
    output: true
    permalink: /engl405/:path/
    label: ENGL405
  course_engl406:
    output: true
    permalink: /engl406/:path/
    label: ENGL406
  course_engl407:
    output: true
    permalink: /engl407/:path/
    label: ENGL407
  course_engl408:
    output: true
    permalink: /engl408/:path/
    label: ENGL408
  course_engl409:
    output: true
    permalink: /engl409/:path/
    label: ENGL409
  course_engl410:
    output: true
    permalink: /engl410/:path/
    label: ENGL410
  course_engl411:
    output: true
    permalink: /engl411/:path/
    label: ENGL411
  course_engl412:
    output: true
    permalink: /engl412/:path/
    label: ENGL412