# Site settings
title: Saylor Academy - GitHub Courses
email: contact@saylor.org
description: > # this means to ignore newlines until "baseurl:"
  Saylor Academy's Legacy Courseware
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost" # the base hostname & protocol for your site
twitter_username: saylordotorg
github_username:  saylordotorg
facebook_username: SaylorFoundation
googleplus_username: 105426497265909285606

# Build settings
markdown: kramdown
#permalink: /:title/

collections:
  course_arth101:
    output: true
    permalink: /arth101/:path/
    label: ARTH101
  course_arth110:
    output: true
    permalink: /arth110/:path/
    label: ARTH110
  course_arth111:
    output: true
    permalink: /arth111/:path/
    label: ARTH111
  course_arth201:
    output: true
    permalink: /arth201/:path/
    label: ARTH201
  course_arth202:
    output: true
    permalink: /arth202/:path/
    label: ARTH202
  course_arth206:
    output: true
    permalink: /arth206/:path/
    label: ARTH206
  course_arth207:
    output: true
    permalink: /arth207/:path/
    label: ARTH207
  course_arth208:
    output: true
    permalink: /arth208/:path/
    label: ARTH208
  course_arth209:
    output: true
    permalink: /arth209/:path/
    label: ARTH209
  coure_arth210:
    output: true
    permalink: /arth210/:path/
    label: ARTH210

